// Runs ONCE per invocation (meant for a GitHub Actions cron schedule, not a
// long-lived process on anyone's personal computer -- see project memory,
// 2026-09-15: a real mint (@vita) sat with no picture for a full day because
// the previous version of this only ran while someone's laptop/session was
// on). Checks the mainnet mini-app collection for mints since the last
// checkpoint (committed in THIS repo, since GitHub Actions runners are
// thrown away after every run -- nowhere local to keep state), renders any
// missing avatar with the SAME generator already live on GitHub Pages, and
// commits+pushes the image+metadata straight into this repo.
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const { chromium } = require('playwright-core');
const { Cell } = require('@ton/core');

const COLLECTION_RAW = '0:fde3aa7bd988ffdd8a3727d8d8a50077648fa96e16f295cb34621627318faaba';
const RENDER_URL = 'https://tima224488-lgtm.github.io/status-avatars-app/';
const RAW_BASE = 'https://raw.githubusercontent.com/tima224488-lgtm/status-avatars-media/main';
const CHECKPOINT_FILE = path.join(__dirname, '.last_seen_index');
const REPO_DIR = __dirname;

function sh(cmd, args) {
    return execFileSync(cmd, args, { cwd: REPO_DIR, stdio: 'pipe' }).toString();
}

async function tonapi(pathAndQuery) {
    const res = await fetch(`https://tonapi.io/v2${pathAndQuery}`);
    if (!res.ok) throw new Error(`tonapi ${pathAndQuery} -> HTTP ${res.status}`);
    return res.json();
}

function loadCheckpoint() {
    try {
        return parseInt(fs.readFileSync(CHECKPOINT_FILE, 'utf8').trim(), 10) || 0;
    } catch (e) {
        return 0;
    }
}

function saveCheckpoint(n) {
    fs.writeFileSync(CHECKPOINT_FILE, String(n));
}

async function getUsernameForIndex(index) {
    const items = await tonapi(`/nfts/collections/${COLLECTION_RAW}/items`);
    const item = items.nft_items.find((i) => i.index === index);
    if (!item) throw new Error(`no item at index ${index} yet`);
    const result = await tonapi(`/blockchain/accounts/${item.address}/methods/username`);
    if (!result.success) throw new Error(`username() call failed for index ${index}`);
    const cellBoc = result.stack[0].cell;
    const cell = Cell.fromBoc(Buffer.from(cellBoc, 'hex'))[0];
    return cell.beginParse().loadStringTail();
}

async function renderAvatar(username, outputPath) {
    const browser = await chromium.launch({ headless: true });
    try {
        const page = await browser.newPage();
        await page.goto(RENDER_URL);
        await page.waitForFunction(() => typeof cfgFromHash === 'function' && typeof render === 'function');
        const dataUrl = await page.evaluate((uname) => {
            const hash = hashOf(uname);
            const cfg = cfgFromHash(uname, hash, true);
            const canvas = document.getElementById('c');
            render(canvas, cfg);
            return canvas.toDataURL('image/png');
        }, username);
        fs.writeFileSync(outputPath, Buffer.from(dataUrl.replace(/^data:image\/png;base64,/, ''), 'base64'));
    } finally {
        await browser.close();
    }
}

async function publishOne(username) {
    const imgDir = path.join(REPO_DIR, 'generated');
    const metaDir = path.join(REPO_DIR, 'meta');
    fs.mkdirSync(imgDir, { recursive: true });
    fs.mkdirSync(metaDir, { recursive: true });

    const pngPath = path.join(imgDir, `${username}.png`);
    await renderAvatar(username, pngPath);

    const metadata = {
        name: `@${username}`,
        description: `Part of The Status Avatars collection — generated by code as vector art (not hand-drawn). Your own personal avatar for @${username}.`,
        image: `${RAW_BASE}/generated/${username}.png`,
        attributes: [{ trait_type: 'source', value: 'mini-app generator' }],
    };
    // No .json extension -- the contract concatenates baseUri + raw username,
    // see status_avatars_item.tact. Getting this wrong = every wallet shows a
    // blank NFT even though the file technically "exists". Bit us once already.
    fs.writeFileSync(path.join(metaDir, username), JSON.stringify(metadata, null, 1));
}

async function main() {
    const collectionData = await tonapi(`/nfts/collections/${COLLECTION_RAW}`);
    const nextIndex = collectionData.next_item_index;
    let lastSeen = loadCheckpoint();
    console.log(`next_item_index=${nextIndex}, last_seen=${lastSeen}`);

    if (nextIndex <= lastSeen) {
        console.log('Nothing new.');
        return;
    }

    let anyPublished = false;
    for (let i = lastSeen; i < nextIndex; i++) {
        try {
            const username = await getUsernameForIndex(i);
            console.log(`New item #${i}: @${username} -- rendering...`);
            await publishOne(username);
            anyPublished = true;
            lastSeen = i + 1;
            saveCheckpoint(lastSeen);
        } catch (e) {
            console.error(`Failed to publish item #${i}: ${e.message || e}`);
            break; // do not skip past a failed item -- retry next scheduled run
        }
    }

    if (anyPublished) {
        sh('git', ['config', 'user.email', 'actions@github.com']);
        sh('git', ['config', 'user.name', 'status-avatars-bot']);
        sh('git', ['add', '-A']);
        try {
            sh('git', ['commit', '-m', 'Auto-publish avatar(s) for new mint(s)']);
        } catch (e) {
            if (!String(e.stdout || e.message).includes('nothing to commit')) throw e;
            return;
        }
        sh('git', ['push']);
        console.log('Pushed.');
    }
}

main().catch((e) => {
    console.error('FATAL:', e);
    process.exit(1);
});
